### PR TITLE
Changed PIP classifiers from beta to stable

### PR DESCRIPTION
**Pull request by peterfarrell**
Things are very stable in the terms of the code base. I'm proposing moving from Beta to Stable in the `setup.py` file so it indicated as such in PyPi and on DjangoPackages.

### CODE REVIEW

**Comment by brki** [comment]
@peterfarrell thanks for the pull request.

I personally don't think that it's ready for a stable release yet.  Migration support is afaik still missing / broken.  Once that's working I'd like to to include native postgresql uuid support, which involves changing the format used for the uuid columns (removes the dashes).

**Comment by peterfarrell** [comment]
Roger.

What's missing with migrations?  We have versionable models that are part of migrations (in Django 1.7+) that work just fine however we don't have any versionable M2M. So I'd be curious about what exactly is broken.

The native Postgres support for UUIDs is a "would be nice" but not required for a stable release IMO.

**Comment by peterfarrell** [comment]
@boydjohnson - what do you know about migrations with CleanerVersion possibly being broken? See comment thread above.

**Comment by boydjohnson** [comment]
@peterfarrell I'm not too familiar with migration in CleanerVersion. I will try making migrations on a versionable model and get back to you.

**Comment by boydjohnson** [comment]
@peterfarrell I made several migrations to an app with versionable models: where the migration was adding a VersionableManyToManyField and where the migration was adding a models.Charfield. There weren't any problems that I identified. @brki What problems with migrations do you know of?

**Comment by raphaelm** [comment]
@boydjohnson FWIW, I use CleanerVersion in a project that makes use of migrations and never encoutered a problem so far.

**Comment by brki** [comment]
Interesting, thanks @all for the all the feedback on that.  Maybe some other commit(s) have fixed the migration problem.  I'll try to find some time this week to look into it again (e.g. see if #53 is still a problem).

**Comment by brki** [comment]
Yep, migrations work for me too.

**Comment by peterfarrell** [comment]
Great!  Is it necessary to have native UUIDField support for Postgres in order to mark as stable?  It's a one 1.8 feature only so we'd have to jury-rig in support for 1.7 (provided that everyone agrees to drop 1.6 as discussed in that other thread).

**Comment by brki** [comment]
Well, in any case, I've got an open pull request for UUIDField support.  Let's see what @maennel has to say about beta vs. stable.  Personally, I'm rather conservative with the stable label, and would prefer to hold off a while longer.

**Comment by maennel** [comment]
Hey @all, I agree with @brki on the subject of declaring CleanerVersion as stable. I think that over the last couple of weeks we had some issues that had quite an impact, and there may be some more. 
However, I also think that we're pretty close to a stable release. We're also using CleanerVersion in a project, that is soon going to prod. So let's leave this point open and take it up in one or two months.

**Comment by peterfarrell** [comment]
Thanks for the info.  It seems very close then.

**Comment by qrilka** [comment]
It's over half a year since CleanerVersion was said to be pretty close to a stable state - why is it still maked ad Beta? Did something unforeseen came up?

**Comment by maennel** [comment]
With the latest bugfixes, I think we can switch to stable. Thanks for your contributions.

**Comment by peterfarrell** [comment]
+1

**Pull request merged**
