### PR TITLE
Fixed errors on Admin view page and Admin history page resulting from…

### PR DESCRIPTION
**Pull request by rossmechanic**
… UUIDs. Also fixed "Restore" button on django-admin change form page
#123 #143

### CODE REVIEW

**Comment by maennel** [comment]
Hey @rossmechanic, thanks a lot for the fix and the tests!

**Comment by rossmechanic** [comment]
@maennel no problem. Did you mean to merge this rather than close it?

**Comment by maennel** [comment]
Oops, of course! Thanks for pointing this out and sorry for the confusion...

**Comment by rossmechanic** [comment]
@maennel No worries. Can you merge now? I can't merge without write access

**Pull request merged**
